[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dnspython>=2.8.0",
    "dotenv>=0.9.9",
    "requests>=2.32.5",
    "scapy>=2.6.1",
]
